package com.hao.show.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hao.show.moudle.main.novel.Entity.NovelChapter;
import com.hao.show.moudle.main.novel.Entity.NovelClassify;
import com.hao.show.moudle.main.novel.Entity.NovelListItemContent;

import com.hao.show.db.dao.NovelChapterDao;
import com.hao.show.db.dao.NovelClassifyDao;
import com.hao.show.db.dao.NovelListItemContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig novelChapterDaoConfig;
    private final DaoConfig novelClassifyDaoConfig;
    private final DaoConfig novelListItemContentDaoConfig;

    private final NovelChapterDao novelChapterDao;
    private final NovelClassifyDao novelClassifyDao;
    private final NovelListItemContentDao novelListItemContentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        novelChapterDaoConfig = daoConfigMap.get(NovelChapterDao.class).clone();
        novelChapterDaoConfig.initIdentityScope(type);

        novelClassifyDaoConfig = daoConfigMap.get(NovelClassifyDao.class).clone();
        novelClassifyDaoConfig.initIdentityScope(type);

        novelListItemContentDaoConfig = daoConfigMap.get(NovelListItemContentDao.class).clone();
        novelListItemContentDaoConfig.initIdentityScope(type);

        novelChapterDao = new NovelChapterDao(novelChapterDaoConfig, this);
        novelClassifyDao = new NovelClassifyDao(novelClassifyDaoConfig, this);
        novelListItemContentDao = new NovelListItemContentDao(novelListItemContentDaoConfig, this);

        registerDao(NovelChapter.class, novelChapterDao);
        registerDao(NovelClassify.class, novelClassifyDao);
        registerDao(NovelListItemContent.class, novelListItemContentDao);
    }
    
    public void clear() {
        novelChapterDaoConfig.clearIdentityScope();
        novelClassifyDaoConfig.clearIdentityScope();
        novelListItemContentDaoConfig.clearIdentityScope();
    }

    public NovelChapterDao getNovelChapterDao() {
        return novelChapterDao;
    }

    public NovelClassifyDao getNovelClassifyDao() {
        return novelClassifyDao;
    }

    public NovelListItemContentDao getNovelListItemContentDao() {
        return novelListItemContentDao;
    }

}
