package com.xb.visitor.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xb.visitor.entity.FaceInfo;
import com.xb.visitor.entity.Feature;

import com.xb.visitor.db.dao.FaceInfoDao;
import com.xb.visitor.db.dao.FeatureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceInfoDaoConfig;
    private final DaoConfig featureDaoConfig;

    private final FaceInfoDao faceInfoDao;
    private final FeatureDao featureDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceInfoDaoConfig = daoConfigMap.get(FaceInfoDao.class).clone();
        faceInfoDaoConfig.initIdentityScope(type);

        featureDaoConfig = daoConfigMap.get(FeatureDao.class).clone();
        featureDaoConfig.initIdentityScope(type);

        faceInfoDao = new FaceInfoDao(faceInfoDaoConfig, this);
        featureDao = new FeatureDao(featureDaoConfig, this);

        registerDao(FaceInfo.class, faceInfoDao);
        registerDao(Feature.class, featureDao);
    }
    
    public void clear() {
        faceInfoDaoConfig.clearIdentityScope();
        featureDaoConfig.clearIdentityScope();
    }

    public FaceInfoDao getFaceInfoDao() {
        return faceInfoDao;
    }

    public FeatureDao getFeatureDao() {
        return featureDao;
    }

}
